version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: jobora-postgres
    environment:
      POSTGRES_DB: jobora_db
      POSTGRES_USER: jobora
      POSTGRES_PASSWORD: jobora123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobora -d jobora_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: jobora-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: