export interface FundingRound {
  round: string
  amount: number
  date: string
  leadInvestors: string[]
  allInvestors: string[]
}

export interface Startup {
  id: string
  name: string
  logoUrl: string
  description: string // expanded from oneLiner to full description
  oneLiner: string
  sector: string[]
  stage: string
  location: string
  foundedYear: number
  employees: string
  website: string
  socialLinks?: {
    linkedin?: string
    twitter?: string
    github?: string
  }
  funding: {
    lastRound: string
    lastRoundDate: string
    totalRaisedUSD: number
    rounds: FundingRound[]
    numberOfInvestors: number
    leadInvestors: string[]
  }
  ipoStatus: "Private" | "Public" | "Acquired"
  acquisitionInfo?: {
    acquirer: string
    amount?: number
    date: string
  }
  revenueRange?: string
  bettingVolume?: number
  investments: string[]
  heatScore: number
}

export interface Investment {
  id: string
  startupId: string
  title: string
  description: string
  targetAmount: number
  raisedAmount: number
  minInvestment: number
  maxInvestment: number
  expectedReturn: string
  timeframe: string
  riskLevel: "Low" | "Medium" | "High"
  investorCount: number
  daysLeft: number
  status: "active" | "funded" | "closed"
  highlights: string[]
}

export interface MyAssets {
  totalInvested: number
  totalValue: number
  totalReturn: number
  investments: any[]
  history: any[]
}

export interface Forecast {
  id: string
  startupId: string
  question: string
  description: string
  resolutionDate: string
  criteria: string
  yesPct: number
  noPct: number
  change24hPct: number
  participation: number
  volume: number
  status: "active" | "resolved"
  category: "funding" | "valuation" | "growth" | "heat" | "ipo"
}

export const mockStartups: Startup[] = [
  {
    id: "su_ai_openai",
    name: "OpenAI",
    logoUrl: "/openai-logo.svg",
    description:
      "Builds advanced AI technologies such as GPT models and ChatGPT, aimed at assisting individuals and organizations in solving complex tasks and improving productivity",
    oneLiner: "Advanced AI technologies and GPT models",
    sector: ["AI", "Generative AI", "Machine Learning", "NLP", "SaaS"],
    stage: "Venture-Series Unknown",
    location: "San Francisco, California, USA",
    foundedYear: 2015,
    employees: "1001–5000",
    website: "https://openai.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/openai",
      twitter: "https://twitter.com/openai",
    },
    funding: {
      lastRound: "Venture-Series Unknown",
      lastRoundDate: "2024-01-01",
      totalRaisedUSD: 11300000000,
      rounds: [],
      numberOfInvestors: 50,
      leadInvestors: ["Microsoft", "Khosla Ventures"],
    },
    ipoStatus: "Private",
    revenueRange: "$1B+ ARR",
    bettingVolume: 15000000,
    investments: [],
    heatScore: 98,
  },
  {
    id: "su_ai_anthropic",
    name: "Anthropic",
    logoUrl: "/anthropic-logo.png",
    description:
      "Research and development company focused on building reliable, interpretable, and steerable AI systems, including the Claude family of models",
    oneLiner: "Reliable and interpretable AI systems",
    sector: ["AI", "Generative AI", "Information Technology", "Machine Learning"],
    stage: "Series F",
    location: "San Francisco, California, USA",
    foundedYear: 2021,
    employees: "1001–5000",
    website: "https://anthropic.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/anthropic",
      twitter: "https://twitter.com/anthropic",
    },
    funding: {
      lastRound: "Series F",
      lastRoundDate: "2024-01-01",
      totalRaisedUSD: 7300000000,
      rounds: [],
      numberOfInvestors: 25,
      leadInvestors: ["Google", "Spark Capital"],
    },
    ipoStatus: "Private",
    revenueRange: "$500M+ ARR",
    bettingVolume: 12000000,
    investments: [],
    heatScore: 95,
  },
  {
    id: "su_ai_stability",
    name: "Stability AI",
    logoUrl: "/stability-ai-logo.png",
    description:
      "Developer of open-source generative models such as Stable Diffusion, enabling image, video, and audio creation at scale",
    oneLiner: "Open-source generative models for media creation",
    sector: ["AI", "Generative AI", "Image Recognition", "IT", "Software"],
    stage: "Corporate Round",
    location: "London, United Kingdom",
    foundedYear: 2019,
    employees: "101–250",
    website: "https://stability.ai",
    socialLinks: {
      linkedin: "https://linkedin.com/company/stability-ai",
      twitter: "https://twitter.com/stabilityai",
    },
    funding: {
      lastRound: "Corporate Round",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 101000000,
      rounds: [],
      numberOfInvestors: 15,
      leadInvestors: ["Coatue", "Lightspeed Venture Partners"],
    },
    ipoStatus: "Private",
    revenueRange: "$10M - $50M ARR",
    bettingVolume: 3500000,
    investments: [],
    heatScore: 87,
  },
  {
    id: "su_ai_huggingface",
    name: "Hugging Face",
    logoUrl: "/hugging-face-logo.svg",
    description:
      "Open-source platform enabling developers to build, train, and deploy machine learning models, widely known for its transformer libraries",
    oneLiner: "Open-source ML platform and transformer libraries",
    sector: ["AI", "Generative AI", "Machine Learning", "NLP", "Open Source", "Software"],
    stage: "Venture-Series Unknown",
    location: "Brooklyn, New York, USA",
    foundedYear: 2016,
    employees: "51–100",
    website: "https://huggingface.co",
    socialLinks: {
      linkedin: "https://linkedin.com/company/huggingface",
      twitter: "https://twitter.com/huggingface",
    },
    funding: {
      lastRound: "Series C",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 235000000,
      rounds: [],
      numberOfInvestors: 20,
      leadInvestors: ["Coatue", "Sequoia Capital"],
    },
    ipoStatus: "Private",
    revenueRange: "$50M - $100M ARR",
    bettingVolume: 4200000,
    investments: [],
    // Added heat score for Hugging Face
    heatScore: 92,
  },
  {
    id: "su_ai_cohere",
    name: "Cohere",
    logoUrl: "/cohere-logo.png",
    description:
      "Provides API access to large language models for enterprises and developers, enabling natural language processing applications at scale",
    oneLiner: "Enterprise LLM API platform",
    sector: ["LLM API", "NLP", "AI Platform"],
    stage: "Series C",
    location: "Toronto, Canada",
    foundedYear: 2019,
    employees: "201–500",
    website: "https://cohere.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/cohere-ai",
      twitter: "https://twitter.com/cohere_ai",
    },
    funding: {
      lastRound: "Series C",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 445000000,
      rounds: [],
      numberOfInvestors: 18,
      leadInvestors: ["Inovia Capital", "Tiger Global"],
    },
    ipoStatus: "Private",
    revenueRange: "$25M - $75M ARR",
    bettingVolume: 2800000,
    investments: [],
    // Added heat score for Cohere
    heatScore: 89,
  },
  {
    id: "su_ai_inflection",
    name: "Inflection AI",
    logoUrl: "/inflection-ai-logo.jpg",
    description: "AI company developing Pi, a personal AI assistant designed for natural and empathetic conversations",
    oneLiner: "Personal AI assistant with empathetic conversations",
    sector: ["Generative AI", "AI Assistants", "NLP"],
    stage: "Series B",
    location: "Palo Alto, California, USA",
    foundedYear: 2022,
    employees: "51–200",
    website: "https://inflection.ai",
    socialLinks: {
      linkedin: "https://linkedin.com/company/inflection-ai",
      twitter: "https://twitter.com/inflectionai",
    },
    funding: {
      lastRound: "Series B",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 1525000000,
      rounds: [],
      numberOfInvestors: 12,
      leadInvestors: ["Microsoft", "NVIDIA"],
    },
    ipoStatus: "Private",
    revenueRange: "$10M - $25M ARR",
    bettingVolume: 3200000,
    investments: [],
    // Added heat score for Inflection AI
    heatScore: 90,
  },
  {
    id: "su_ai_mistral",
    name: "Mistral AI",
    logoUrl: "/mistral-ai-logo.png",
    description: "Builds open-source, compact, and efficient large language models tailored for European markets",
    oneLiner: "Open-source efficient LLMs for Europe",
    sector: ["Generative AI", "Foundation Models", "Open Source"],
    stage: "Series A",
    location: "Paris, France",
    foundedYear: 2023,
    employees: "51–100",
    website: "https://mistral.ai",
    socialLinks: {
      linkedin: "https://linkedin.com/company/mistral-ai",
      twitter: "https://twitter.com/mistralai",
    },
    funding: {
      lastRound: "Series A",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 415000000,
      rounds: [],
      numberOfInvestors: 15,
      leadInvestors: ["General Catalyst", "Lightspeed Venture Partners"],
    },
    ipoStatus: "Private",
    revenueRange: "$5M - $15M ARR",
    bettingVolume: 2100000,
    investments: [],
    // Added heat score for Mistral AI
    heatScore: 88,
  },
  {
    id: "su_ai_perplexity",
    name: "Perplexity AI",
    logoUrl: "/perplexity-logo.svg",
    description:
      "AI-powered search engine that delivers direct, conversational answers with sources, blending generative AI and traditional search",
    oneLiner: "AI-powered conversational search engine",
    sector: ["AI Assistant", "Generative AI", "Search Engine"],
    stage: "Early Stage",
    location: "San Francisco, California, USA",
    foundedYear: 2022,
    employees: "51–100",
    website: "https://perplexity.ai",
    socialLinks: {
      linkedin: "https://linkedin.com/company/perplexity-ai",
      twitter: "https://twitter.com/perplexity_ai",
    },
    funding: {
      lastRound: "Series B",
      lastRoundDate: "2024-01-01",
      totalRaisedUSD: 165000000,
      rounds: [],
      numberOfInvestors: 20,
      leadInvestors: ["IVP", "NEA"],
    },
    ipoStatus: "Private",
    revenueRange: "$10M - $25M ARR",
    bettingVolume: 1800000,
    investments: [],
    // Added heat score for Perplexity AI
    heatScore: 91,
  },
  {
    id: "su_ai_runway",
    name: "Runway",
    logoUrl: "/runway-logo.jpg",
    description: "Provides creative tools for generating and editing videos using advanced machine learning techniques",
    oneLiner: "AI-powered video generation and editing tools",
    sector: ["Generative Video", "Computer Vision", "Machine Learning"],
    stage: "Series C",
    location: "New York, USA",
    foundedYear: 2018,
    employees: "101–250",
    website: "https://runwayml.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/runwayml",
      twitter: "https://twitter.com/runwayml",
    },
    funding: {
      lastRound: "Series C",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 237000000,
      rounds: [],
      numberOfInvestors: 25,
      leadInvestors: ["Google Ventures", "Felicis"],
    },
    ipoStatus: "Private",
    revenueRange: "$25M - $50M ARR",
    bettingVolume: 2900000,
    investments: [],
    // Added heat score for Runway
    heatScore: 85,
  },
  {
    id: "su_ai_adept",
    name: "Adept AI",
    logoUrl: "/adept-logo.jpg",
    description:
      "Developer of ACT-1, a large action model that automates software workflows and enhances human productivity",
    oneLiner: "Large action models for workflow automation",
    sector: ["Generative AI", "Large Action Models", "AI Productivity"],
    stage: "Series B",
    location: "San Francisco, California, USA",
    foundedYear: 2021,
    employees: "51–100",
    website: "https://adept.ai",
    socialLinks: {
      linkedin: "https://linkedin.com/company/adept-ai",
      twitter: "https://twitter.com/adept_ai",
    },
    funding: {
      lastRound: "Series B",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 415000000,
      rounds: [],
      numberOfInvestors: 15,
      leadInvestors: ["General Catalyst", "Spark Capital"],
    },
    ipoStatus: "Private",
    revenueRange: "$5M - $15M ARR",
    bettingVolume: 1900000,
    investments: [],
    // Added heat score for Adept AI
    heatScore: 86,
  },
  {
    id: "su_ai_scale",
    name: "Scale AI",
    logoUrl: "/scale-ai-logo.jpg",
    description:
      "Provides high-quality training data and infrastructure to accelerate the development of artificial intelligence models",
    oneLiner: "AI training data and infrastructure platform",
    sector: ["Data Labeling", "AI Infrastructure", "Machine Learning"],
    stage: "Series F",
    location: "San Francisco, California, USA",
    foundedYear: 2016,
    employees: "1001–5000",
    website: "https://scale.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/scale-ai",
      twitter: "https://twitter.com/scaleapi",
    },
    funding: {
      lastRound: "Series F",
      lastRoundDate: "2024-01-01",
      totalRaisedUSD: 1005000000,
      rounds: [],
      numberOfInvestors: 30,
      leadInvestors: ["Accel", "Index Ventures"],
    },
    ipoStatus: "Private",
    revenueRange: "$250M - $500M ARR",
    bettingVolume: 8500000,
    investments: [],
    // Added heat score for Scale AI
    heatScore: 93,
  },
  {
    id: "su_ai_databricks",
    name: "Databricks",
    logoUrl: "/databricks-logo.svg",
    description:
      "Provides a unified data and AI platform for managing, analyzing, and deploying large-scale data and ML applications",
    oneLiner: "Unified data and AI lakehouse platform",
    sector: ["Big Data", "Data Analytics", "Machine Learning", "Lakehouse Platform"],
    stage: "Series I",
    location: "San Francisco, California, USA",
    foundedYear: 2013,
    employees: "5000+",
    website: "https://databricks.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/databricks",
      twitter: "https://twitter.com/databricks",
    },
    funding: {
      lastRound: "Series I",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 3500000000,
      rounds: [],
      numberOfInvestors: 40,
      leadInvestors: ["CapitalG", "Coatue"],
    },
    ipoStatus: "Private",
    revenueRange: "$1B+ ARR",
    bettingVolume: 12000000,
    investments: [],
    // Added heat score for Databricks
    heatScore: 96,
  },
  {
    id: "su_ai_jasper",
    name: "Jasper",
    logoUrl: "/jasper-logo.jpg",
    description: "AI-powered platform for generating marketing copy, blog posts, and other digital content",
    oneLiner: "AI content generation for marketing",
    sector: ["Generative AI", "Content Creation", "Marketing Automation"],
    stage: "Series A",
    location: "Austin, Texas, USA",
    foundedYear: 2021,
    employees: "100–200",
    website: "https://jasper.ai",
    socialLinks: {
      linkedin: "https://linkedin.com/company/jasper-ai",
      twitter: "https://twitter.com/jasper_ai",
    },
    funding: {
      lastRound: "Series A",
      lastRoundDate: "2022-01-01",
      totalRaisedUSD: 125000000,
      rounds: [],
      numberOfInvestors: 12,
      leadInvestors: ["Insight Partners", "Coatue"],
    },
    ipoStatus: "Private",
    revenueRange: "$50M - $100M ARR",
    bettingVolume: 1600000,
    investments: [],
    // Added heat score for Jasper
    heatScore: 84,
  },
  {
    id: "su_ai_deepl",
    name: "DeepL",
    logoUrl: "/deepl-logo.svg",
    description: "Developer of neural machine translation technology and writing tools used worldwide",
    oneLiner: "Neural machine translation and writing tools",
    sector: ["Machine Translation", "NLP"],
    stage: "Corporate Round",
    location: "Cologne, Germany",
    foundedYear: 2017,
    employees: "501–1000",
    website: "https://deepl.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/deepl",
      twitter: "https://twitter.com/deepl",
    },
    funding: {
      lastRound: "Corporate Round",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 300000000,
      rounds: [],
      numberOfInvestors: 8,
      leadInvestors: ["IVP", "Bessemer Venture Partners"],
    },
    ipoStatus: "Private",
    revenueRange: "$100M - $250M ARR",
    bettingVolume: 2400000,
    investments: [],
    // Added heat score for DeepL
    heatScore: 88,
  },
  {
    id: "su_ai_elevenlabs",
    name: "ElevenLabs",
    logoUrl: "/elevenlabs-logo.jpg",
    description: "Specializes in generative audio and synthetic speech technology for realistic voice generation",
    oneLiner: "Generative audio and synthetic speech technology",
    sector: ["Generative Audio", "Speech Synthesis"],
    stage: "Series A",
    location: "New York, USA",
    foundedYear: 2022,
    employees: "51–100",
    website: "https://elevenlabs.io",
    socialLinks: {
      linkedin: "https://linkedin.com/company/elevenlabs",
      twitter: "https://twitter.com/elevenlabsio",
    },
    funding: {
      lastRound: "Series A",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 80000000,
      rounds: [],
      numberOfInvestors: 15,
      leadInvestors: ["Andreessen Horowitz", "Nat Friedman"],
    },
    ipoStatus: "Private",
    revenueRange: "$25M - $50M ARR",
    bettingVolume: 1800000,
    investments: [],
    // Added heat score for ElevenLabs
    heatScore: 87,
  },
  {
    id: "su_ai_synthesia",
    name: "Synthesia",
    logoUrl: "/synthesia-logo.jpg",
    description: "Creates synthetic video content with AI avatars for training, marketing, and communications",
    oneLiner: "AI video generation with synthetic avatars",
    sector: ["AI Video", "Synthetic Media"],
    stage: "Series C",
    location: "London, United Kingdom",
    foundedYear: 2017,
    employees: "101–250",
    website: "https://synthesia.io",
    socialLinks: {
      linkedin: "https://linkedin.com/company/synthesia",
      twitter: "https://twitter.com/synthesiaio",
    },
    funding: {
      lastRound: "Series C",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 156000000,
      rounds: [],
      numberOfInvestors: 20,
      leadInvestors: ["Accel", "Kleiner Perkins"],
    },
    ipoStatus: "Private",
    revenueRange: "$50M - $100M ARR",
    bettingVolume: 2200000,
    investments: [],
    // Added heat score for Synthesia
    heatScore: 89,
  },
  {
    id: "su_ai_did",
    name: "D-ID",
    logoUrl: "/d-id-logo.jpg",
    description: 'Developer of synthetic media technology, known for its "talking photos" and AI video solutions',
    oneLiner: "Synthetic media and talking photos technology",
    sector: ["Deepfake Prevention", "AI Video", "Computer Vision"],
    stage: "Series B",
    location: "Tel Aviv, Israel",
    foundedYear: 2017,
    employees: "51–100",
    website: "https://d-id.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/d-id",
      twitter: "https://twitter.com/d_id_",
    },
    funding: {
      lastRound: "Series B",
      lastRoundDate: "2022-01-01",
      totalRaisedUSD: 68000000,
      rounds: [],
      numberOfInvestors: 18,
      leadInvestors: ["Pitango Venture Capital", "Viola Ventures"],
    },
    ipoStatus: "Private",
    revenueRange: "$10M - $25M ARR",
    bettingVolume: 1300000,
    investments: [],
    // Added heat score for D-ID
    heatScore: 82,
  },
  {
    id: "su_ai_silo",
    name: "Silo AI",
    logoUrl: "/silo-ai-logo.jpg",
    description: "Provides tailored AI solutions and consulting services for enterprises in Europe",
    oneLiner: "Enterprise AI consulting and solutions",
    sector: ["AI Consulting", "Computer Vision", "NLP"],
    stage: "Early Stage",
    location: "Helsinki, Finland",
    foundedYear: 2017,
    employees: "51–200",
    website: "https://silo.ai",
    socialLinks: {
      linkedin: "https://linkedin.com/company/silo-ai",
      twitter: "https://twitter.com/siloai",
    },
    funding: {
      lastRound: "Series A",
      lastRoundDate: "2021-01-01",
      totalRaisedUSD: 28000000,
      rounds: [],
      numberOfInvestors: 10,
      leadInvestors: ["Atomico", "LowerCarbon Capital"],
    },
    ipoStatus: "Private",
    revenueRange: "$10M - $25M ARR",
    bettingVolume: 900000,
    investments: [],
    // Added heat score for Silo AI
    heatScore: 78,
  },
  {
    id: "su_ai_pinecone",
    name: "Pinecone",
    logoUrl: "/pinecone-logo.jpg",
    description: "Provides vector database infrastructure enabling semantic search and retrieval for AI applications",
    oneLiner: "Vector database for AI applications",
    sector: ["Vector Databases", "Search Infrastructure", "AI Embeddings"],
    stage: "Series B",
    location: "New York, USA",
    foundedYear: 2019,
    employees: "51–200",
    website: "https://pinecone.io",
    socialLinks: {
      linkedin: "https://linkedin.com/company/pinecone-io",
      twitter: "https://twitter.com/pinecone",
    },
    funding: {
      lastRound: "Series B",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 138000000,
      rounds: [],
      numberOfInvestors: 15,
      leadInvestors: ["Andreessen Horowitz", "ICONIQ Growth"],
    },
    ipoStatus: "Private",
    revenueRange: "$25M - $50M ARR",
    bettingVolume: 1900000,
    investments: [],
    // Added heat score for Pinecone
    heatScore: 90,
  },
  {
    id: "su_ai_wandb",
    name: "Weights & Biases",
    logoUrl: "/weights-biases-logo.svg",
    description: "Provides tools for tracking experiments, datasets, and models for machine learning development",
    oneLiner: "ML experiment tracking and model management",
    sector: ["ML Ops", "Experiment Tracking"],
    stage: "Series C",
    location: "San Francisco, California, USA",
    foundedYear: 2018,
    employees: "201–500",
    website: "https://wandb.ai",
    socialLinks: {
      linkedin: "https://linkedin.com/company/wandb",
      twitter: "https://twitter.com/weights_biases",
    },
    funding: {
      lastRound: "Series C",
      lastRoundDate: "2022-01-01",
      totalRaisedUSD: 200000000,
      rounds: [],
      numberOfInvestors: 20,
      leadInvestors: ["Insight Partners", "Battery Ventures"],
    },
    ipoStatus: "Private",
    revenueRange: "$50M - $100M ARR",
    bettingVolume: 2100000,
    investments: [],
    // Added heat score for Weights & Biases
    heatScore: 88,
  },
  {
    id: "su_ai_langchain",
    name: "LangChain",
    logoUrl: "/langchain-logo.jpg",
    description: "Open-source framework that enables developers to build applications powered by large language models",
    oneLiner: "LLM application development framework",
    sector: ["Developer Tools", "AI Frameworks", "LLM Orchestration"],
    stage: "Early Stage",
    location: "San Francisco, California, USA",
    foundedYear: 2022,
    employees: "11–50",
    website: "https://langchain.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/langchain",
      twitter: "https://twitter.com/langchainai",
    },
    funding: {
      lastRound: "Series A",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 25000000,
      rounds: [],
      numberOfInvestors: 12,
      leadInvestors: ["Sequoia Capital", "Benchmark"],
    },
    ipoStatus: "Private",
    revenueRange: "$5M - $15M ARR",
    bettingVolume: 1100000,
    investments: [],
    // Added heat score for LangChain
    heatScore: 91,
  },
  {
    id: "su_ai_replit",
    name: "Replit",
    logoUrl: "/replit-logo.svg",
    description: "Online IDE with collaborative coding features and an AI assistant called Ghostwriter",
    oneLiner: "Collaborative cloud IDE with AI coding assistant",
    sector: ["Cloud IDE", "Generative Coding", "Developer Tools"],
    stage: "Series B",
    location: "San Francisco, California, USA",
    foundedYear: 2016,
    employees: "101–250",
    website: "https://replit.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/replit",
      twitter: "https://twitter.com/replit",
    },
    funding: {
      lastRound: "Series B",
      lastRoundDate: "2022-01-01",
      totalRaisedUSD: 155000000,
      rounds: [],
      numberOfInvestors: 18,
      leadInvestors: ["Coatue", "SV Angel"],
    },
    ipoStatus: "Private",
    revenueRange: "$25M - $50M ARR",
    bettingVolume: 1700000,
    investments: [],
    // Added heat score for Replit
    heatScore: 87,
  },
  {
    id: "su_ai_glean",
    name: "Glean",
    logoUrl: "/glean-ai-logo.jpg",
    description: "Enterprise search engine with generative AI-powered answers for workplace knowledge discovery",
    oneLiner: "AI-powered enterprise search and knowledge discovery",
    sector: ["Enterprise Search", "AI Assistant"],
    stage: "Series D",
    location: "Palo Alto, California, USA",
    foundedYear: 2019,
    employees: "201–500",
    website: "https://glean.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/glean-search",
      twitter: "https://twitter.com/glean_search",
    },
    funding: {
      lastRound: "Series D",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 260000000,
      rounds: [],
      numberOfInvestors: 22,
      leadInvestors: ["Kleiner Perkins", "Lightspeed Venture Partners"],
    },
    ipoStatus: "Private",
    revenueRange: "$50M - $100M ARR",
    bettingVolume: 1800000,
    investments: [],
    // Added heat score for Glean
    heatScore: 90,
  },
  {
    id: "su_ai_pika",
    name: "Pika Labs",
    logoUrl: "/pika-labs-logo.jpg",
    description: "Startup focused on AI-generated video and creative tools for content creators",
    oneLiner: "AI video generation for content creators",
    sector: ["AI Video", "Generative Media"],
    stage: "Pre-Seed",
    location: "San Francisco, California, USA",
    foundedYear: 2023,
    employees: "11–50",
    website: "https://createwithpika.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/pika-labs",
      twitter: "https://twitter.com/pika_labs",
    },
    funding: {
      lastRound: "Pre-Seed",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 55000000,
      rounds: [],
      numberOfInvestors: 8,
      leadInvestors: ["Lightspeed Venture Partners", "Nat Friedman"],
    },
    ipoStatus: "Private",
    revenueRange: "$1M - $5M ARR",
    bettingVolume: 800000,
    investments: [],
    // Added heat score for Pika Labs
    heatScore: 85,
  },
  {
    id: "su_ai_aleph",
    name: "Aleph Alpha",
    logoUrl: "/aleph-alpha-logo.jpg",
    description: "Developer of large-scale multilingual language models for enterprise and government use",
    oneLiner: "Multilingual LLMs for enterprise and government",
    sector: ["Generative AI", "Multilingual Models", "Enterprise AI"],
    stage: "Series B",
    location: "Heidelberg, Germany",
    foundedYear: 2019,
    employees: "101–250",
    website: "https://aleph-alpha.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/aleph-alpha",
      twitter: "https://twitter.com/aleph_alpha",
    },
    funding: {
      lastRound: "Series B",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 500000000,
      rounds: [],
      numberOfInvestors: 15,
      leadInvestors: ["Bosch Ventures", "SAP.iO"],
    },
    ipoStatus: "Private",
    revenueRange: "$25M - $50M ARR",
    bettingVolume: 1600000,
    investments: [],
    // Added heat score for Aleph Alpha
    heatScore: 88,
  },
  {
    id: "su_ai_character",
    name: "Character AI",
    logoUrl: "/character-ai-logo.jpg",
    description: "Enables users to create and interact with virtual AI characters for entertainment and productivity",
    oneLiner: "Virtual AI characters for entertainment",
    sector: ["Generative AI", "Conversational Agents", "Consumer Apps"],
    stage: "Series A",
    location: "Menlo Park, California, USA",
    foundedYear: 2021,
    employees: "51–100",
    website: "https://character.ai",
    socialLinks: {
      linkedin: "https://linkedin.com/company/character-ai",
      twitter: "https://twitter.com/character_ai",
    },
    funding: {
      lastRound: "Series A",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 193500000,
      rounds: [],
      numberOfInvestors: 12,
      leadInvestors: ["Andreessen Horowitz", "SV Angel"],
    },
    ipoStatus: "Private",
    revenueRange: "$10M - $25M ARR",
    bettingVolume: 1900000,
    investments: [],
    // Added heat score for Character AI
    heatScore: 90,
  },
  {
    id: "su_ai_lightricks",
    name: "Lightricks",
    logoUrl: "/lightricks-logo.jpg",
    description: "Developer of creative apps like Facetune and Photoleap, incorporating generative AI features",
    oneLiner: "Creative apps with generative AI features",
    sector: ["Photo Editing", "Generative AI", "Mobile Apps"],
    stage: "Series D",
    location: "Jerusalem, Israel",
    foundedYear: 2013,
    employees: "501–1000",
    website: "https://lightricks.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/lightricks",
      twitter: "https://twitter.com/lightricks",
    },
    funding: {
      lastRound: "Series D",
      lastRoundDate: "2021-01-01",
      totalRaisedUSD: 335000000,
      rounds: [],
      numberOfInvestors: 25,
      leadInvestors: ["Insight Partners", "Hanaco Venture Capital"],
    },
    ipoStatus: "Private",
    revenueRange: "$100M - $250M ARR",
    bettingVolume: 1400000,
    investments: [],
    // Added heat score for Lightricks
    heatScore: 86,
  },
  {
    id: "su_ai_001",
    name: "NovaGraph",
    logoUrl: "/novagraph-logo.jpg",
    description:
      "NovaGraph is revolutionizing data infrastructure with the world's fastest vector database designed for real-time Retrieval-Augmented Generation (RAG) at enterprise scale. Our proprietary indexing algorithms deliver sub-millisecond query times while handling billions of high-dimensional vectors, enabling AI applications that were previously impossible.",
    oneLiner: "Vector database for real-time RAG at scale",
    sector: ["AI", "DevTools"],
    stage: "Seed",
    location: "San Francisco, US",
    foundedYear: 2023,
    employees: "11-50",
    website: "https://novagraph.example",
    socialLinks: {
      linkedin: "https://linkedin.com/company/novagraph",
      twitter: "https://twitter.com/novagraph",
      github: "https://github.com/novagraph",
    },
    funding: {
      lastRound: "Seed",
      lastRoundDate: "2025-04-15",
      totalRaisedUSD: 8500000,
      rounds: [
        {
          round: "Pre-seed",
          amount: 1200000,
          date: "2023-08-10",
          leadInvestors: ["Accel Partners"],
          allInvestors: ["Accel Partners", "Y Combinator", "Angel investors"],
        },
        {
          round: "Seed",
          amount: 7300000,
          date: "2025-04-15",
          leadInvestors: ["Andreessen Horowitz", "GV"],
          allInvestors: ["Andreessen Horowitz", "GV", "Accel Partners", "Founders Fund"],
        },
      ],
      numberOfInvestors: 12,
      leadInvestors: ["Andreessen Horowitz", "GV", "Accel Partners"],
    },
    ipoStatus: "Private",
    revenueRange: "$1M - $5M ARR",
    bettingVolume: 2400000,
    investments: ["inv_nv_001"],
    // Added heat score for NovaGraph
    heatScore: 80,
  },
  {
    id: "su_ai_deepl_write",
    name: "DeepL Write",
    logoUrl: "/deepl-write-logo.jpg",
    description: "AI-powered writing assistant for improving clarity, fluency, and style in multiple languages",
    oneLiner: "AI writing assistant for multiple languages",
    sector: ["Generative AI", "Writing Assistant"],
    stage: "Early Stage",
    location: "Cologne, Germany",
    foundedYear: 2021,
    employees: "11–50",
    website: "https://deepl.com/write",
    socialLinks: {
      linkedin: "https://linkedin.com/company/deepl",
      twitter: "https://twitter.com/deepl",
    },
    funding: {
      lastRound: "Early Stage",
      lastRoundDate: "2022-01-01",
      totalRaisedUSD: 15000000,
      rounds: [],
      numberOfInvestors: 5,
      leadInvestors: ["DeepL SE"],
    },
    ipoStatus: "Private",
    revenueRange: "$5M - $15M ARR",
    bettingVolume: 700000,
    investments: [],
    // Added heat score for DeepL Write
    heatScore: 79,
  },
  {
    id: "su_ai_poe",
    name: "Quora – Poe",
    logoUrl: "/poe-logo.jpg",
    description: "Provides users with access to multiple AI models in one interface for chat, search, and productivity",
    oneLiner: "Multi-AI model interface for chat and productivity",
    sector: ["AI Chatbot", "Aggregated LLM Interface"],
    stage: "Internal Startup",
    location: "Mountain View, California, USA",
    foundedYear: 2023,
    employees: "51–100",
    website: "https://poe.com",
    socialLinks: {
      linkedin: "https://linkedin.com/company/quora",
      twitter: "https://twitter.com/quora",
    },
    funding: {
      lastRound: "Internal Startup",
      lastRoundDate: "2023-01-01",
      totalRaisedUSD: 0,
      rounds: [],
      numberOfInvestors: 0,
      leadInvestors: ["Quora"],
    },
    ipoStatus: "Private",
    revenueRange: "$10M - $25M ARR",
    bettingVolume: 1200000,
    investments: [],
    // Added heat score for Poe
    heatScore: 83,
  },
  {
    id: "su_fintech_001",
    name: "PayFlow",
    logoUrl: "/payflow-logo.jpg",
    description:
      "PayFlow transforms invoice management for small and medium businesses through advanced AI automation. Our platform reduces invoice processing time by 90% while improving accuracy and cash flow visibility. We serve over 10,000 SMBs across North America with our intelligent accounts receivable solution.",
    oneLiner: "AI-powered invoice automation for SMBs",
    sector: ["Fintech", "SaaS"],
    stage: "Series A",
    location: "New York, US",
    foundedYear: 2022,
    employees: "51-100",
    website: "https://payflow.example",
    socialLinks: {
      linkedin: "https://linkedin.com/company/payflow",
      twitter: "https://twitter.com/payflow",
    },
    funding: {
      lastRound: "Series A",
      lastRoundDate: "2024-11-20",
      totalRaisedUSD: 15000000,
      rounds: [
        {
          round: "Pre-seed",
          amount: 800000,
          date: "2022-06-15",
          leadInvestors: ["Techstars"],
          allInvestors: ["Techstars", "Angel investors"],
        },
        {
          round: "Seed",
          amount: 4200000,
          date: "2023-03-20",
          leadInvestors: ["Sequoia Capital"],
          allInvestors: ["Sequoia Capital", "Stripe", "Plaid"],
        },
        {
          round: "Series A",
          amount: 10000000,
          date: "2024-11-20",
          leadInvestors: ["Sequoia Capital", "Index Ventures"],
          allInvestors: ["Sequoia Capital", "Index Ventures", "Stripe", "Plaid", "Bessemer Venture Partners"],
        },
      ],
      numberOfInvestors: 18,
      leadInvestors: ["Sequoia Capital", "Index Ventures", "Stripe"],
    },
    ipoStatus: "Private",
    revenueRange: "$10M - $25M ARR",
    bettingVolume: 5600000,
    investments: ["inv_pf_001"],
    // Added heat score for PayFlow
    heatScore: 85,
  },
  {
    id: "su_climate_001",
    name: "GreenTech Solutions",
    logoUrl: "/greentech-logo.jpg",
    description:
      "GreenTech Solutions develops cutting-edge smart grid optimization technology using machine learning to maximize renewable energy efficiency. Our AI algorithms predict energy demand patterns and automatically balance grid loads, reducing waste by up to 30% while ensuring stable power delivery.",
    oneLiner: "Smart grid optimization using machine learning",
    sector: ["Climate", "Energy"],
    stage: "Pre-seed",
    location: "Berlin, Germany",
    foundedYear: 2024,
    employees: "1-10",
    website: "https://greentech.example",
    socialLinks: {
      linkedin: "https://linkedin.com/company/greentech-solutions",
      twitter: "https://twitter.com/greentechsol",
    },
    funding: {
      lastRound: "Pre-seed",
      lastRoundDate: "2024-08-10",
      totalRaisedUSD: 2000000,
      rounds: [
        {
          round: "Pre-seed",
          amount: 2000000,
          date: "2024-08-10",
          leadInvestors: ["Climate Capital"],
          allInvestors: ["Climate Capital", "Breakthrough Energy Ventures", "Angel investors"],
        },
      ],
      numberOfInvestors: 8,
      leadInvestors: ["Climate Capital", "Breakthrough Energy Ventures"],
    },
    ipoStatus: "Private",
    bettingVolume: 890000,
    investments: ["inv_gt_001"],
    // Added heat score for GreenTech Solutions
    heatScore: 75,
  },
  {
    id: "su_health_001",
    name: "MediCore",
    logoUrl: "/medicore-logo.jpg",
    description:
      "MediCore leverages advanced AI and computer vision to revolutionize diagnostic imaging for early disease detection. Our FDA-approved platform analyzes medical scans with 95% accuracy, helping radiologists detect cancer, neurological disorders, and cardiovascular diseases months earlier than traditional methods.",
    oneLiner: "AI-powered diagnostic imaging for early disease detection",
    sector: ["Healthcare", "AI"],
    stage: "Series A",
    location: "Boston, US",
    foundedYear: 2021,
    employees: "51-100",
    website: "https://medicore.example",
    socialLinks: {
      linkedin: "https://linkedin.com/company/medicore",
      twitter: "https://twitter.com/medicore",
    },
    funding: {
      lastRound: "Series A",
      lastRoundDate: "2024-09-15",
      totalRaisedUSD: 18000000,
      rounds: [
        {
          round: "Seed",
          amount: 3500000,
          date: "2022-04-20",
          leadInvestors: ["GV", "Andreessen Horowitz"],
          allInvestors: ["GV", "Andreessen Horowitz", "Johnson & Johnson Innovation"],
        },
        {
          round: "Series A",
          amount: 14500000,
          date: "2024-09-15",
          leadInvestors: ["GV", "Kleiner Perkins"],
          allInvestors: [
            "GV",
            "Kleiner Perkins",
            "Andreessen Horowitz",
            "Johnson & Johnson Innovation",
            "Mayo Clinic Ventures",
          ],
        },
      ],
      numberOfInvestors: 15,
      leadInvestors: ["GV", "Kleiner Perkins", "Andreessen Horowitz"],
    },
    ipoStatus: "Private",
    revenueRange: "$5M - $15M ARR",
    bettingVolume: 2500000,
    investments: ["inv_mc_001"],
    // Added heat score for MediCore
    heatScore: 88,
  },
  {
    id: "su_mobility_001",
    name: "UrbanRide",
    logoUrl: "/urbanride-logo.jpg",
    description:
      "UrbanRide is pioneering autonomous micro-mobility solutions for sustainable urban transportation. Our self-driving e-scooters and bikes use advanced computer vision and IoT sensors to navigate city streets safely while providing carbon-neutral last-mile transportation for over 1 million users.",
    oneLiner: "Autonomous micro-mobility solutions for urban transport",
    sector: ["Mobility", "Hardware"],
    stage: "Seed",
    location: "Amsterdam, Netherlands",
    foundedYear: 2023,
    employees: "11-50",
    website: "https://urbanride.example",
    socialLinks: {
      linkedin: "https://linkedin.com/company/urbanride",
      twitter: "https://twitter.com/urbanride",
    },
    funding: {
      lastRound: "Seed",
      lastRoundDate: "2024-12-01",
      totalRaisedUSD: 6500000,
      rounds: [
        {
          round: "Pre-seed",
          amount: 1200000,
          date: "2023-09-15",
          leadInvestors: ["Atomico"],
          allInvestors: ["Atomico", "Creandum", "Angel investors"],
        },
        {
          round: "Seed",
          amount: 5300000,
          date: "2024-12-01",
          leadInvestors: ["Atomico", "Balderton Capital"],
          allInvestors: ["Atomico", "Balderton Capital", "Creandum", "BMW i Ventures"],
        },
      ],
      numberOfInvestors: 12,
      leadInvestors: ["Atomico", "Balderton Capital", "BMW i Ventures"],
    },
    ipoStatus: "Private",
    revenueRange: "$1M - $5M ARR",
    bettingVolume: 1200000,
    investments: ["inv_ur_001"],
    // Added heat score for UrbanRide
    heatScore: 80,
  },
  {
    id: "su_ecommerce_001",
    name: "ShopAI",
    logoUrl: "/shopai-logo.jpg",
    description:
      "ShopAI transforms online shopping experiences with a personalized shopping assistant powered by computer vision. Our platform analyzes customer behavior and preferences to offer tailored recommendations, enhancing conversion rates and customer satisfaction. We partner with major retailers to provide a seamless shopping experience for millions of users.",
    oneLiner: "Personalized shopping assistant powered by computer vision",
    sector: ["E-commerce", "AI"],
    stage: "Pre-seed",
    location: "London, UK",
    foundedYear: 2024,
    employees: "1-10",
    website: "https://shopai.example",
    socialLinks: {
      linkedin: "https://linkedin.com/company/shopai",
      twitter: "https://twitter.com/shopai",
    },
    funding: {
      lastRound: "Pre-seed",
      lastRoundDate: "2024-10-20",
      totalRaisedUSD: 1800000,
      rounds: [
        {
          round: "Pre-seed",
          amount: 1800000,
          date: "2024-10-20",
          leadInvestors: ["Y Combinator"],
          allInvestors: ["Y Combinator", "Angel investors"],
        },
      ],
      numberOfInvestors: 5,
      leadInvestors: ["Y Combinator"],
    },
    ipoStatus: "Private",
    revenueRange: "$500K - $2M ARR",
    bettingVolume: 800000,
    investments: ["inv_sa_001"],
    // Added heat score for ShopAI
    heatScore: 78,
  },
  {
    id: "su_crypto_001",
    name: "BlockSecure",
    logoUrl: "/blocksecure-logo.jpg",
    description:
      "BlockSecure is a leading enterprise blockchain security and compliance platform, ensuring secure and transparent transactions for businesses worldwide. Our platform integrates with major blockchain networks and provides real-time monitoring and risk assessment tools, protecting assets worth over $50M.",
    oneLiner: "Enterprise blockchain security and compliance platform",
    sector: ["Crypto", "Security"],
    stage: "Series A",
    location: "Singapore",
    foundedYear: 2022,
    employees: "51-100",
    website: "https://blocksecure.example",
    socialLinks: {
      linkedin: "https://linkedin.com/company/blocksecure",
      twitter: "https://twitter.com/blocksecure",
    },
    funding: {
      lastRound: "Series A",
      lastRoundDate: "2024-07-30",
      totalRaisedUSD: 22000000,
      rounds: [
        {
          round: "Pre-seed",
          amount: 4000000,
          date: "2022-07-15",
          leadInvestors: ["Dragonfly Capital"],
          allInvestors: ["Dragonfly Capital", "Angel investors"],
        },
        {
          round: "Seed",
          amount: 8000000,
          date: "2023-02-20",
          leadInvestors: ["Sequoia Capital"],
          allInvestors: ["Sequoia Capital", "Bain Capital", "Dragonfly Capital"],
        },
        {
          round: "Series A",
          amount: 10000000,
          date: "2024-07-30",
          leadInvestors: ["Sequoia Capital", "Bain Capital"],
          allInvestors: ["Sequoia Capital", "Bain Capital", "Dragonfly Capital", "Bessemer Venture Partners"],
        },
      ],
      numberOfInvestors: 20,
      leadInvestors: ["Sequoia Capital", "Bain Capital", "Dragonfly Capital"],
    },
    ipoStatus: "Private",
    revenueRange: "$10M - $25M ARR",
    bettingVolume: 3000000,
    investments: ["inv_bs_001"],
    // Added heat score for BlockSecure
    heatScore: 82,
  },
  {
    id: "su_edtech_001",
    name: "LearnLab",
    logoUrl: "/learnlab-logo.jpg",
    description:
      "LearnLab is an adaptive learning platform for STEM education, using AI to personalize learning experiences for students. Our platform tracks individual progress and adjusts content in real-time, ensuring that each student masters the material at their own pace. We serve over 500 schools and have seen a 40% improvement in learning outcomes.",
    oneLiner: "Adaptive learning platform for STEM education",
    sector: ["EdTech", "AI"],
    stage: "Seed",
    location: "Toronto, Canada",
    foundedYear: 2023,
    employees: "11-50",
    website: "https://learnlab.example",
    socialLinks: {
      linkedin: "https://linkedin.com/company/learnlab",
      twitter: "https://twitter.com/learnlab",
    },
    funding: {
      lastRound: "Seed",
      lastRoundDate: "2024-06-10",
      totalRaisedUSD: 4200000,
      rounds: [
        {
          round: "Pre-seed",
          amount: 4200000,
          date: "2024-06-10",
          leadInvestors: ["Y Combinator"],
          allInvestors: ["Y Combinator", "Angel investors"],
        },
      ],
      numberOfInvestors: 7,
      leadInvestors: ["Y Combinator"],
    },
    ipoStatus: "Private",
    revenueRange: "$1M - $5M ARR",
    bettingVolume: 1800000,
    investments: ["inv_ll_001"],
    // Added heat score for LearnLab
    heatScore: 79,
  },
  {
    id: "su_biotech_001",
    name: "GeneTech",
    logoUrl: "/genetech-logo.jpg",
    description:
      "GeneTech is at the forefront of gene therapy solutions for rare genetic disorders, offering innovative treatments backed by cutting-edge research. Our platform has successfully completed Phase II trials and has received orphan drug designation, bringing hope to patients worldwide.",
    oneLiner: "Gene therapy solutions for rare genetic disorders",
    sector: ["Biotech", "Healthcare"],
    stage: "Series B",
    location: "Basel, Switzerland",
    foundedYear: 2020,
    employees: "101-250",
    website: "https://genetech.example",
    socialLinks: {
      linkedin: "https://linkedin.com/company/genetech",
      twitter: "https://twitter.com/genetech",
    },
    funding: {
      lastRound: "Series B",
      lastRoundDate: "2024-03-25",
      totalRaisedUSD: 45000000,
      rounds: [
        {
          round: "Pre-seed",
          amount: 5000000,
          date: "2021-06-15",
          leadInvestors: ["Climate Capital"],
          allInvestors: ["Climate Capital", "Angel investors"],
        },
        {
          round: "Seed",
          amount: 15000000,
          date: "2022-09-20",
          leadInvestors: ["Sequoia Capital"],
          allInvestors: ["Sequoia Capital", "Bain Capital", "Climate Capital"],
        },
        {
          round: "Series A",
          amount: 20000000,
          date: "2023-01-10",
          leadInvestors: ["Sequoia Capital", "Bain Capital"],
          allInvestors: ["Sequoia Capital", "Bain Capital", "Climate Capital", "Founders Fund"],
        },
        {
          round: "Series B",
          amount: 45000000,
          date: "2024-03-25",
          leadInvestors: ["Sequoia Capital", "Bain Capital"],
          allInvestors: [
            "Sequoia Capital",
            "Bain Capital",
            "Climate Capital",
            "Founders Fund",
            "Johnson & Johnson Innovation",
          ],
        },
      ],
      numberOfInvestors: 25,
      leadInvestors: ["Sequoia Capital", "Bain Capital", "Climate Capital"],
    },
    ipoStatus: "Private",
    revenueRange: "$50M - $100M ARR",
    bettingVolume: 5000000,
    investments: ["inv_gt_002"],
    // Added heat score for GeneTech
    heatScore: 89,
  },
  {
    id: "su_robotics_001",
    name: "RoboAssist",
    logoUrl: "/placeholder.svg?height=40&width=40",
    description:
      "RoboAssist is a leader in collaborative robots for warehouse automation, using AI to enhance efficiency and reduce labor costs. Our robots work alongside human operators to improve accuracy and speed in inventory management, logistics, and manufacturing processes.",
    oneLiner: "Collaborative robots for warehouse automation",
    sector: ["Robotics", "Hardware"],
    stage: "Series A",
    location: "Munich, Germany",
    foundedYear: 2022,
    employees: "51-100",
    website: "https://roboassist.example",
    socialLinks: {
      linkedin: "https://linkedin.com/company/roboassist",
      twitter: "https://twitter.com/roboassist",
    },
    funding: {
      lastRound: "Series A",
      lastRoundDate: "2024-05-18",
      totalRaisedUSD: 16500000,
      rounds: [
        {
          round: "Pre-seed",
          amount: 2500000,
          date: "2022-01-15",
          leadInvestors: ["Techstars"],
          allInvestors: ["Techstars", "Angel investors"],
        },
        {
          round: "Seed",
          amount: 6000000,
          date: "2023-04-20",
          leadInvestors: ["Andreessen Horowitz"],
          allInvestors: ["Andreessen Horowitz", "GV", "Techstars"],
        },
        {
          round: "Series A",
          amount: 16500000,
          date: "2024-05-18",
          leadInvestors: ["Andreessen Horowitz", "GV"],
          allInvestors: ["Andreessen Horowitz", "GV", "Techstars", "Founders Fund"],
        },
      ],
      numberOfInvestors: 15,
      leadInvestors: ["Andreessen Horowitz", "GV", "Techstars"],
    },
    ipoStatus: "Private",
    revenueRange: "$10M - $25M ARR",
    bettingVolume: 2400000,
    investments: ["inv_ra_001"],
    // Added heat score for RoboAssist
    heatScore: 84,
  },
  {
    id: "su_foodtech_001",
    name: "PlantPro",
    logoUrl: "/plantpro-logo.jpg",
    description:
      "PlantPro is a plant-based protein manufacturing company, dedicated to producing sustainable and high-quality protein products for the food industry. Our industrial-scale facilities use advanced biotechnology to create protein sources that are cost-effective and environmentally friendly, catering to the growing demand for plant-based diets.",
    oneLiner: "Plant-based protein manufacturing at industrial scale",
    sector: ["FoodTech", "Climate"],
    stage: "Seed",
    location: "Copenhagen, Denmark",
    foundedYear: 2023,
    employees: "11-50",
    website: "https://plantpro.example",
    socialLinks: {
      linkedin: "https://linkedin.com/company/plantpro",
      twitter: "https://twitter.com/plantpro",
    },
    funding: {
      lastRound: "Seed",
      lastRoundDate: "2024-08-05",
      totalRaisedUSD: 7800000,
      rounds: [
        {
          round: "Pre-seed",
          amount: 7800000,
          date: "2024-08-05",
          leadInvestors: ["Climate Capital"],
          allInvestors: ["Climate Capital", "Angel investors"],
        },
      ],
      numberOfInvestors: 9,
      leadInvestors: ["Climate Capital"],
    },
    ipoStatus: "Private",
    revenueRange: "$1M - $5M ARR",
    bettingVolume: 1000000,
    investments: ["inv_pp_001"],
    // Added heat score for PlantPro
    heatScore: 77,
  },
  {
    id: "su_space_001",
    name: "OrbitTech",
    logoUrl: "/orbittech-logo.jpg",
    description:
      "OrbitTech is developing a small satellite constellation for Earth observation, providing valuable data for climate monitoring, agriculture, and urban planning. Our satellites offer global coverage and are designed to be cost-effective and scalable, making space technology accessible to a wide range of applications.",
    oneLiner: "Small satellite constellation for Earth observation",
    sector: ["Space", "Hardware"],
    stage: "Series A",
    location: "Los Angeles, US",
    foundedYear: 2021,
    employees: "51-100",
    website: "https://orbittech.example",
    socialLinks: {
      linkedin: "https://linkedin.com/company/orbittech",
      twitter: "https://twitter.com/orbittech",
    },
    funding: {
      lastRound: "Series A",
      lastRoundDate: "2024-04-12",
      totalRaisedUSD: 28000000,
      rounds: [
        {
          round: "Pre-seed",
          amount: 4000000,
          date: "2022-02-10",
          leadInvestors: ["Techstars"],
          allInvestors: ["Techstars", "Angel investors"],
        },
        {
          round: "Seed",
          amount: 14000000,
          date: "2023-07-15",
          leadInvestors: ["Andreessen Horowitz"],
          allInvestors: ["Andreessen Horowitz", "GV", "Techstars"],
        },
        {
          round: "Series A",
          amount: 28000000,
          date: "2024-04-12",
          leadInvestors: ["Andreessen Horowitz", "GV"],
          allInvestors: ["Andreessen Horowitz", "GV", "Techstars", "Founders Fund"],
        },
      ],
      numberOfInvestors: 20,
      leadInvestors: ["Andreessen Horowitz", "GV", "Techstars"],
    },
    ipoStatus: "Private",
    revenueRange: "$10M - $25M ARR",
    bettingVolume: 3500000,
    investments: ["inv_ot_001"],
    // Added heat score for OrbitTech
    heatScore: 83,
  },
]

// Real forecast data that matches actual startups
export const mockRealForecasts: Forecast[] = [
  {
    id: "forecast_001",
    startupId: "su_ai_anthropic",
    question: "Will Anthropic raise Series B by Q2 2025?",
    description: "Based on current growth trajectory and market conditions",
    resolutionDate: "2025-06-30",
    criteria: "Official announcement of Series B funding round completion",
    yesPct: 72,
    noPct: 28,
    change24hPct: 2.3,
    participation: 1247,
    volume: 45200,
    status: "active",
    category: "funding",
  },
  {
    id: "forecast_002",
    startupId: "su_ai_anthropic",
    question: "Anthropic valuation to exceed $500M by end of 2025?",
    description: "Current valuation estimated at $280M post-Series A",
    resolutionDate: "2025-12-31",
    criteria: "Official valuation announcement or funding round disclosure",
    yesPct: 58,
    noPct: 42,
    change24hPct: -1.8,
    participation: 892,
    volume: 32800,
    status: "active",
    category: "valuation",
  },
  {
    id: "forecast_003",
    startupId: "su_ai_openai",
    question: "OpenAI to go public by 2026?",
    description: "Speculation around IPO timing given current market position",
    resolutionDate: "2026-12-31",
    criteria: "Official IPO filing or public trading commencement",
    yesPct: 34,
    noPct: 66,
    change24hPct: -0.5,
    participation: 2156,
    volume: 89400,
    status: "active",
    category: "ipo",
  },
  {
    id: "forecast_004",
    startupId: "su_ai_character",
    question: "Character AI valuation to reach $10B by Q4 2025?",
    description: "Rapid user growth and engagement metrics suggest high potential",
    resolutionDate: "2025-10-31",
    criteria: "Funding round or acquisition announcement with $10B+ valuation",
    yesPct: 41,
    noPct: 59,
    change24hPct: 3.7,
    participation: 1834,
    volume: 67200,
    status: "active",
    category: "valuation",
  },
  {
    id: "forecast_005",
    startupId: "su_ai_scale",
    question: "Scale AI to achieve $1B ARR by 2026?",
    description: "Current revenue trajectory and enterprise adoption rates",
    resolutionDate: "2026-12-31",
    criteria: "Official revenue disclosure or credible third-party reporting",
    yesPct: 67,
    noPct: 33,
    change24hPct: 1.2,
    participation: 1456,
    volume: 54300,
    status: "active",
    category: "growth",
  },
  {
    id: "forecast_006",
    startupId: "su_ai_perplexity",
    question: "Perplexity AI to be acquired by major tech company in 2025?",
    description: "Growing interest from Google, Microsoft, and other tech giants",
    resolutionDate: "2025-12-31",
    criteria: "Official acquisition announcement by FAANG or similar company",
    yesPct: 29,
    noPct: 71,
    change24hPct: -2.1,
    participation: 987,
    volume: 38900,
    status: "active",
    category: "funding",
  },
  {
    id: "forecast_007",
    startupId: "su_ai_runway",
    question: "Runway to launch consumer video editing app by Q3 2025?",
    description: "Expansion beyond professional tools to consumer market",
    resolutionDate: "2025-09-30",
    criteria: "Public release of consumer-focused video editing application",
    yesPct: 78,
    noPct: 22,
    change24hPct: 4.2,
    participation: 743,
    volume: 29100,
    status: "active",
    category: "growth",
  },
  {
    id: "forecast_008",
    startupId: "su_ai_mistral",
    question: "Mistral AI to become Europe's most valuable AI startup by 2026?",
    description: "Competition with other European AI companies for market leadership",
    resolutionDate: "2026-12-31",
    criteria: "Highest valuation among European-based AI startups",
    yesPct: 52,
    noPct: 48,
    change24hPct: 0.8,
    participation: 1123,
    volume: 41700,
    status: "active",
    category: "valuation",
  },
]

// Update the export to use real forecasts instead of investments
export const mockForecasts: Forecast[] = mockRealForecasts

export const mockMyAssets: MyAssets = {
  totalInvested: 25000,
  totalValue: 32500,
  totalReturn: 7500,
  investments: [],
  history: [],
}
